### ISSUE TITLE
Support Ansible 2.0

### ISSUE THREAD

**Issue by avelis** [Stouts/Stouts.python#7]
The `with_items` changes syntax in Ansible 2.0 or greater. I might be able to make a PR later but wanted to write an issue for it.

**Comment by yyoshiki41** [comment]
This issue has been already solved in https://github.com/Stouts/Stouts.python/commit/c2712473afe32e0edaf78912e577808d4fcdba22 .

So, we can close this 👍 

---

Maybe, the problem pointed out in this issue is below.

> Bare variables in with_ loops should instead use the "{ {var }}" syntax, which helps eliminate ambiguity.

http://docs.ansible.com/ansible/latest/porting_guide_2.0.html#deprecated
